apiVersion: v2
name: aws-ebs-csi-driver
description: AWS EBS CSI Driver Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0
dependencies:
- name: aws-ebs-csi-driver
  version: 2.33.0
  repository: https://github.com/kubernetes-sigs
