apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gha-app-secret
  namespace: gha-runner-scale-set
spec:
  refreshInterval: 240h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gha-app-secret
    creationPolicy: Owner
  data:
  - secretKey: github_app_id
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: gha_app_self_hosted_runner
      property: github_app_id
  - secretKey: github_app_installation_id
    remoteRef:
      key: gha_app_self_hosted_runner
      property: github_app_installation_id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: github_app_private_key
    remoteRef:
      key: gha_app_self_hosted_runner
      property: github_app_private_key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
